import type { Metadata } from "next";
import localFont from "next/font/local";
import { cn } from "@/lib/utils";
import "./globals.css";

const pretendard = localFont({
  adjustFontFallback: "Arial",
  src: [
    {
      path: "/fonts/Pretendard-Regular.woff2",
      weight: "400",
    },
    {
      path: "/fonts/Pretendard-Medium.woff2",
      weight: "500",
    },
    {
      path: "/fonts/Pretendard-SemiBold.woff2",
      weight: "600",
    },
    {
      path: "/fonts/Pretendard-Bold.woff2",
      weight: "700",
    },
  ],
  preload: true,
  display: "swap",
  variable: "--font-base",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={cn(pretendard.className, pretendard.variable)}>
        {children}
      </body>
    </html>
  );
}
